application: cp-live
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /sanitycheck
  script: sanitycheck.app
  
- url: /
  script: teaser.app

- url: .*
  script: cp.app
  
libraries:
- name: jinja2
  version: latest
  
