application: cp-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on
- appstats: on

handlers:
- url: /static
  static_dir: static

- url: /sanitycheck
  script: sanitycheck.app

- url: /fblogin
  script: fblogin.app


- url: .*
  script: cp.app
  
libraries:
- name: jinja2
  version: latest