application: helloworld
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /sanitycheck
  script: sanitycheck.app

- url: .*
  script: cp.app
  
libraries:
- name: jinja2
  version: latest